-- Ensure required extension for UUID generation
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Ensure schema exists (minimal, idempotent for initdb)
CREATE TABLE IF NOT EXISTS admins (
    id UUID PRIMARY KEY,
    email VARCHAR(180) NOT NULL,
    password_hash VARCHAR(255) NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_admin_email ON admins (email);

CREATE TABLE IF NOT EXISTS events (
    id UUID PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    location VARCHAR(255) NOT NULL,
    seats INT NOT NULL,
    image VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
    refresh_token VARCHAR(128) NOT NULL,
    username VARCHAR(255) NOT NULL,
    valid TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_refresh_token ON refresh_tokens (refresh_token);

CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY,
    email VARCHAR(180) NOT NULL,
    name VARCHAR(255),
    role VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_user_email ON users (email);

CREATE TABLE IF NOT EXISTS reservations (
    id UUID PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    event_id UUID NOT NULL,
    user_id UUID
);
CREATE INDEX IF NOT EXISTS idx_res_event ON reservations (event_id);
CREATE INDEX IF NOT EXISTS idx_res_user ON reservations (user_id);

CREATE TABLE IF NOT EXISTS webauthn_credentials (
    id UUID PRIMARY KEY,
    credential_data TEXT NOT NULL,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    last_used_at TIMESTAMP(0) WITHOUT TIME ZONE,
    user_id UUID NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_webauthn_user ON webauthn_credentials (user_id);

CREATE TABLE IF NOT EXISTS messenger_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    body TEXT NOT NULL,
    headers TEXT NOT NULL,
    queue_name VARCHAR(190) NOT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    delivered_at TIMESTAMP(0) WITHOUT TIME ZONE
);
CREATE INDEX IF NOT EXISTS idx_messenger_queue ON messenger_messages (queue_name, available_at, delivered_at, id);

-- Foreign keys
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_res_event') THEN
        ALTER TABLE reservations
            ADD CONSTRAINT fk_res_event FOREIGN KEY (event_id) REFERENCES events (id) NOT DEFERRABLE;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_res_user') THEN
        ALTER TABLE reservations
            ADD CONSTRAINT fk_res_user FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE;
    END IF;
END $$;
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_webauthn_user') THEN
        ALTER TABLE webauthn_credentials
            ADD CONSTRAINT fk_webauthn_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE;
    END IF;
END $$;

-- Reset tables (works on fresh init; adjust if FK constraints change)
TRUNCATE TABLE refresh_tokens RESTART IDENTITY CASCADE;
TRUNCATE TABLE reservations RESTART IDENTITY CASCADE;
TRUNCATE TABLE webauthn_credentials RESTART IDENTITY CASCADE;
TRUNCATE TABLE admins RESTART IDENTITY CASCADE;
TRUNCATE TABLE users RESTART IDENTITY CASCADE;
TRUNCATE TABLE events RESTART IDENTITY CASCADE;
TRUNCATE TABLE messenger_messages RESTART IDENTITY CASCADE;

-- Seed users/admins/events/reservations with generated UUIDs (password: Password123!)
WITH seed_users AS (
    SELECT gen_random_uuid() AS id, 'admin@example.com' AS email, 'Admin User' AS name, 'ROLE_ADMIN' AS role, '$2y$13$9E6Ch12yvDqOiiMHDL/95.fz1RMgZcbQfVIAtF5NCz7r3A3w5Dq9W' AS pwd
    UNION ALL
    SELECT gen_random_uuid(), 'user@example.com', 'Regular User', 'ROLE_USER', '$2y$13$9E6Ch12yvDqOiiMHDL/95.fz1RMgZcbQfVIAtF5NCz7r3A3w5Dq9W'
), ins_users AS (
    INSERT INTO users (id, email, name, role, password_hash)
    SELECT id, email, name, role, pwd FROM seed_users
    RETURNING id, email, role
), ins_admins AS (
    INSERT INTO admins (id, email, password_hash)
    SELECT id, email, '$2y$13$9E6Ch12yvDqOiiMHDL/95.fz1RMgZcbQfVIAtF5NCz7r3A3w5Dq9W'
    FROM ins_users
    WHERE role = 'ROLE_ADMIN'
    RETURNING id, email
), seed_events AS (
    SELECT gen_random_uuid() AS id, 'Tech Conference 2025' AS title, 'A two-day conference about emerging tech trends.' AS description, NOW() + INTERVAL '30 days' AS date, 'Conference Center A' AS location, 250 AS seats, 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80' AS image
    UNION ALL
    SELECT gen_random_uuid(), 'Music Festival', 'Outdoor festival featuring multiple bands and food trucks.', NOW() + INTERVAL '45 days', 'City Park', 500, 'https://images.unsplash.com/photo-1507878866276-a947ef722fee?auto=format&fit=crop&w=1200&q=80'
    UNION ALL
    SELECT gen_random_uuid(), 'Startup Pitch Night', 'Local startups pitch to investors and community members.', NOW() + INTERVAL '14 days', 'Innovation Hub', 120, 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1200&q=80'
    UNION ALL
    SELECT gen_random_uuid(), 'Food Truck Rally', 'A gourmet lineup of local food trucks with live DJ sets.', NOW() + INTERVAL '10 days', 'Riverfront Plaza', 300, 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=80'
    UNION ALL
    SELECT gen_random_uuid(), 'Art & Wine Night', 'Gallery showcase with curated wines and artist talks.', NOW() + INTERVAL '21 days', 'Modern Art Gallery', 150, 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?auto=format&fit=crop&w=1200&q=80'
    UNION ALL
    SELECT gen_random_uuid(), 'Hackathon Weekend', '48-hour product sprint for developers and designers.', NOW() + INTERVAL '7 days', 'Innovation Hub', 200, 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80'
    UNION ALL
    SELECT gen_random_uuid(), 'Charity Run 10K', 'Community run to support local education initiatives.', NOW() + INTERVAL '25 days', 'City Stadium', 800, 'https://images.unsplash.com/photo-1508609349937-5ec4ae374ebf?auto=format&fit=crop&w=1200&q=80'
    UNION ALL
    SELECT gen_random_uuid(), 'Startup Workshop', 'Hands-on sessions for early-stage founders and teams.', NOW() + INTERVAL '18 days', 'Co-Working Loft', 120, 'https://images.unsplash.com/photo-1545239351-1141bd82e8a6?auto=format&fit=crop&w=1200&q=80'
    UNION ALL
    SELECT gen_random_uuid(), 'Jazz Night', 'An evening of live jazz with craft cocktails.', NOW() + INTERVAL '12 days', 'Blue Note Lounge', 180, 'https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=1200&q=80'
    UNION ALL
    SELECT gen_random_uuid(), 'Outdoor Film Screening', 'Open-air cinema featuring indie short films.', NOW() + INTERVAL '20 days', 'Central Park Lawn', 400, 'https://images.unsplash.com/photo-1464375117522-1311d6a5b81f?auto=format&fit=crop&w=1200&q=80'
), ins_events AS (
    INSERT INTO events (id, title, description, date, location, seats, image)
    SELECT id, title, description, date, location, seats, image FROM seed_events
    RETURNING id, title
), seed_reservations AS (
    SELECT 'Alice Doe' AS name, 'alice@example.com' AS email, '+1234567890' AS phone, NOW() - INTERVAL '1 day' AS created_at, 'Tech Conference 2025' AS event_title, 'user@example.com' AS user_email
    UNION ALL
    SELECT 'Bob Smith', 'bob@example.com', '+1987654321', NOW() - INTERVAL '2 days', 'Music Festival', 'user@example.com'
    UNION ALL
    SELECT 'Charlie Admin', 'admin@example.com', '+12125550123', NOW() - INTERVAL '3 days', 'Startup Pitch Night', 'admin@example.com'
)
INSERT INTO reservations (id, name, email, phone, created_at, event_id, user_id)
SELECT
    gen_random_uuid(),
    r.name,
    r.email,
    r.phone,
    r.created_at,
    e.id,
    u.id
FROM seed_reservations r
JOIN ins_events e ON e.title = r.event_title
JOIN ins_users u ON u.email = r.user_email;